server:
  port: 8082

spring:
  datasource:
        url: jdbc:mysql://localhost:3306/seven-color?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


mybatis:
    type-aliases-package: com.github.dalianghe.*.entity
    mapper-locations: classpath*:mappers/*.xml
    check-config-location: true

mapper:
    mappers:
        - com.github.dalianghe.core.base.BaseMapper
    not-empty: false
    identity: MYSQL


# PageHelperConfig 可以替代此方案
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql